spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie1
    username: root
    password: 123456

server:

  port: 8000

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id